### ISSUE TITLE
List of Rules getting VERY long, mostly deprecated, and some not yet active, pls consider adding dates

### ISSUE THREAD

**Issue by clancger** [phax/phive-rules#13]
In a recent version for the list of supported Validation rules there were approx 660 different rules across Peppol and other domains, most of which long since deprecated, as well as some which eg were published in May, but not ready to use till July. 
Can you please consider adding a date to future publications to signify from when its valid, as the naming / numbering is very inconsistent and makes it difficult for an implementer to decode which is the one to use at a given time

**Comment by phax** [comment]
Definitively a good suggestion - if I would only know. In some cases - like Peppol EU - it is quite clear when certain rules are in effect, but for other it is quite unclear.
That's why classes like `PeppolValidation3_14_0` have a constant `VALID_PER` that defines the date at when they take effect.
A "to date" cannot be provided yet (with good conscience), because the owner of the rules might decide to change the release cycle. So that is imho the best thing I can come up with.

However it might be helpful to add a `valid from` and a `valid to` field to the underlying `ValidationExecutorSet` - so it is more clear and no manual decision needs to be taken.

**Comment by phax** [comment]
Indeed I now added a "Status" object for every VES in form of a `ValidationExecutorSetStatus` object.
It contains the following elements:
* A state (like `active` or `deprecated`)
* An optional "valid from" date time
* An optional "valid to" date time
* An optional deprecation reason
* Optional replacement coordinates for the new version
* A way to track status changes
